config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  resources :courses
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root to: 'pages#home'
  resources 'dashboards', only: [:index]
  get 'users/profile'
  get 'users/show', as: 'profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :room, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :courses, dependent: :destroy
  has_many :teachers, through: :courses


  def name
    @name = "#{first_name} #{last_name}"
  end

  validates :name, presence: false
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :courses
  has_many :students, through: :courses

  def name
    @name = "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :username
  has_many :courses, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :registerable, :confirmable

  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  def name
    @name = "#{first_name} #{last_name}"
  end

  def avatar_thumbnail
    if avatar.attached?
      avatar
    else
      "/default_profile.jpg"
    end
  end

  private

  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_profile.jpg'
            )
          ), filename: 'default_profile.jpg',
          content_type: 'image/jpg'
        )
    end
  end

# This method is active at the moment to avoid confirmable from applying.
# It should be activated at a later stage of the application.
# To skip required confirmation all-together

  protected

  def confirmation_required?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :first_name, :last_name, :city, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :first_name, :last_name, :city, :phone])
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    dashboards_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  def index
    @courses = Course.all
  end

  def show
    @user = current_user
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :start_date, :end_date, :start_time, :end_time, :shift, :price, :user_id, :teacher_id, :student_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @message = "Welcome to CASA Language School!"
    user = current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save
    redirect_to request.referrer

    SendMessageJob.perform_later(@message)
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:content, :user_id, :room_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
    @rooms = Room.all
    render 'index'
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if (emoji = Emoji.find_by_alias($1))
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}", skip_pipeline: true)}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/courses/_form.html.erb
<div class="col">
  <%= simple_form_for(@course) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :description, as: :text, input_html: {rows: 10, cols: 10} %>
      <div class="row">
        <div class="col mr-n2">
          <%= f.input :start_date, as: :string, input_html: {class: "datepicker", id: "range_start"} %>
        </div>
        <div class="col ml-n2">
          <%= f.input :end_date, as: :string, input_html: {class: "datepicker", id: "range_end"} %>
        </div>
      </div>
      <div class="row">
        <div class="col mr-n2">
          <%# end_time = start_time.strftime("%H:%M") %>
          <%= f.input :start_time, as: :time, minute_step: 15 %>
        </div>
        <div class="col mr-n2">
          <%# end_time = end_time.strftime("%H:%M") %>
          <%= f.input :end_time, as: :time, minute_step: 15 %>
        </div>
      </div>
      <div class="row">
        <div class="col mr-n2">
          <%= f.input :shift, label: "Time of Day", collection: [['Morning'], ['Afternoon'], ['Evening'], ['Special']] %>
        </div>
        <div class="col mr-n2">
          <%= f.input :price %>
        </div>
      </div>
      <div class="row">
        <div class="col mr-n2">
          <%= f.association :teacher, required: false, label: "Select Teachers" %>
        </div>
        <div class="col mr-n2">
          <%= f.association :user, required: false, label: "Administrator" %>
        </div>
      </div>
      <%= f.association :student, required: false, label: "Students" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn-create" %>
    </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<div class="container">
  <h1 class="mt-5 text-center">Editing Course</h1>

  <%= render 'form', course: @course %>
<br>
<!--   <%#= link_to 'Show', @course, class: "btn-info" %> |
  <%#= link_to 'Back', courses_path, class: "btn-info" %> -->
</div>

<br>
<br>
<br>
<br>

app/views/courses/new.html.erb
<div class="container">
  <h1 class="mt-5 text-center">Add a New Course</h1>

  <%= render 'form', course: @course %>

  <%#= link_to 'Back', courses_path %>
</div>

<br>
<br>
<br>
<br>

app/views/dashboards/index.html.erb
<div class="container">
  <div class="text-center mt-5">
    <h1><%= @message %></h1>
    <p>Please read the following instructions carefully to be able to make the best use of our platform.</p>
  </div>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LmsCasa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%#= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
  <%= render "shared/footer" %>

</html>

app/views/messages/_form.html.erb
<%#= simple_form_for(@message) do |f| %>
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%#= f.input :content %>
    <%#= f.association :user %>
    <%#= f.association :room %>
  </div>

  <div class="form-actions">
    <%#= f.button :submit %>
  </div>
<%# end %>

<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :room_id, value: room.id %>

  <div class="input-group">
    <%= form.text_field :content, placeholder: "Type your message here...", class: 'form-control' %>
    <div class="input-group-append">
      <%= form.submit "Send", class: "btn btn-flat ml-3" %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="message mb-2 <%= 'me' if message.user == current_user %>">
  <div class="content-container">
    <div class="content">
      <%= message.content %>
      <%#= emojify message.content %>
    </div>
    <div class="author">
      <%= message.user.username %>
    </div>
  </div>
</div>

app/views/messages/_mine.html.erb
<div class="message mb-2 me">
  <div class="content-container">
    <div class="content">
      <%= message.content %>
    </div>
    <div class="author">
      <%= message.user.username %>
    </div>
  </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message mb-2">
  <div class="content-container">
    <div class="content">
      <%= message.content %>
    </div>
    <div class="author">
      <%= message.user.username %>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="container-fluid">
  <h1>Messages</h1>

  <table>
    <thead>
      <tr>
        <th>Content</th>
        <th>User</th>
        <th>Room</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= message.content %></td>
          <td><%= message.user_id %></td>
          <td><%= message.room_id %></td>
          <td><%= link_to 'Show', message %></td>
          <td><%= link_to 'Edit', edit_message_path(message) %></td>
          <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Message', new_message_path %>

</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/messages/new.html.erb
<div class="container">
  <h1>New Message</h1>

  <%= render 'form', message: @message %>

  <%= link_to 'Back', messages_path %>

</div>

app/views/messages/show.html.erb
<div class="container">
  <p>
    <strong>Content:</strong>
    <%= @message.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @message.user_id %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= @message.room_id %>
  </p>

  <%= link_to 'Edit', edit_message_path(@message) %> |
  <%= link_to 'Back', messages_path %>

</div>

app/views/pages/home.html.erb
<!-- <style>
  body {background-color: #fce7d1;}
</style> -->
<% if user_signed_in? %>
<!-- <div class="banner-sign-in" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1546410531-bb4caa6b424d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80);">-->
<!-- <div class="banner-sign-in" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%#= asset_url 'IMG_0580.png' %>');">
  <div class="container justify-content-center">
    <div class="text-center">
          <h1>Welcome to
            <div class="d-inline-flex">
              <h1 style="font-family: 'Reggae One', cursive; color: #D01117;">C</h1>
              <h1 style="font-family: 'Reggae One', cursive; color: #F3F0F9;">A</h1>
              <h1 style="font-family: 'Reggae One', cursive; color: #E3B505;">S</h1>
              <h1 style="font-family: 'Reggae One', cursive; color: #1EDD88;">A</h1>
            </div>
     Language School</h1>
      <p>Change your life and learn a new language at one of the best language schools in Germany!</p>
    </div>
  </div>
</div> -->

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
     <div class="banner-sign-in" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.1)), url('<%= asset_url 'IMG_0580.png' %>');">
      <div class="container justify-content-center">
        <div class="text-center">
              <h1>Welcome to
                <div class="d-inline-flex">
                  <h1 style="font-family: 'Reggae One', cursive; color: #D01117;">C</h1>
                  <h1 style="font-family: 'Reggae One', cursive; color: #F3F0F9;">A</h1>
                  <h1 style="font-family: 'Reggae One', cursive; color: #E3B505;">S</h1>
                  <h1 style="font-family: 'Reggae One', cursive; color: #1EDD88;">A</h1>
                </div>
         Language School</h1>
          <p>Change your life and learn a new language at one of the best language schools in Germany!</p>
        </div>
      </div>
     </div>
    </div>
    <div class="carousel-item">
     <div class="banner-sign-in" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.1)), url('<%= asset_url 'IMG_0586.png' %>');"></div>
    </div>
    <div class="carousel-item">
     <div class="banner-sign-in" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.1)), url('<%= asset_url '15024_1082.jpg' %>');"></div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>
<br>

<div class="container-cards mt-5 mb-5">
  <h2 class="mb-5 text-center">Select one of the options</h2>
  <div class="row row-cols-1 row-cols-md-4 g-3">
    <div class="col mb-3">
      <%= link_to users_profile_path, class: "clickable-card" do %>
      <div class="card h-100 card-home education">
        <img src="https://images.unsplash.com/photo-1511367461989-f85a21fda167?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1189&q=80" class="card-img-top" alt="..." style="width: 100% !important; height: 200px !important;">
        <div class="card-body">
          <h5 class="card-title">Profile</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
<!--         <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div> -->
      </div>
      <% end %>
    </div>
    <div class="col mb-3">
      <%= link_to courses_path, class: "clickable-card" do %>
      <div class="card h-100 card-home">
        <img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1002&q=80" class="card-img-top" alt="..." style="width: 100% !important; height: 200px !important;">
        <div class="card-body">
          <h5 class="card-title">Courses</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        </div>
<!--         <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div> -->
      </div>
      <% end %>
    </div>
    <div class="col mb-3">
      <%= link_to users_profile_path, class: "clickable-card" do %>
      <div class="card h-100 card-home">
        <img src="https://images.unsplash.com/photo-1588605360336-77ac8ee6fc53?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" class="card-img-top" alt="..." style="width: 100% !important; height: 200px !important;">
        <div class="card-body">
          <h5 class="card-title">Challenges</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        </div>
<!--         <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div> -->
      </div>
      <% end %>
    </div>
    <div class="col mb-3">
      <%= link_to users_profile_path, class: "clickable-card" do %>
      <div class="card h-100 card-home">
        <img src="https://images.unsplash.com/photo-1504639725590-34d0984388bd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" class="card-img-top" alt="..." style="width: 100% !important; height: 200px !important;">
        <div class="card-body">
          <h5 class="card-title">Resources</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        </div>
<!--         <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div> -->
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>
<div class="container-fluid mb-5">
  <div class="home-belt mb-5 mt-5 d-flex aligh-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/reserve/uZYSV4nuQeyq64azfVIn_15130980706_64134efc6e_o.jpg?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1047&q=80);">
    <div class="container">
    <div class="text-center home-belt-text">
      <h2>"He who knows no foreign languages knows nothing of his own."</h2>
      <p>Name of the Writer</p>
    </div>
  </div>
</div>
<br>
<br>
<br>
<% else %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.4)), url('<%= asset_url 'IMG_0586.png' %>');">
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1589395937658-0557e7d89fad?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80);">
 -->  <div class="container justify-content-center">
    <div class="text-center">
      <h1>Welcome to
        <div class="d-inline-flex">
          <h1 style="font-family: 'Reggae One', cursive; color: #D01117;">C</h1>
          <h1 style="font-family: 'Reggae One', cursive; color: #F3F0F9;">A</h1>
          <h1 style="font-family: 'Reggae One', cursive; color: #E3B505;">S</h1>
          <h1 style="font-family: 'Reggae One', cursive; color: #1EDD88;">A</h1>
        </div>
   Language School</h1>
      <p>Change your life and learn a new language at one of the best language schools in Germany!</p>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-ghost mr-2" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-ghost" %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/new.html.erb
<div class="container">
  <h1>New Room</h1>

  <%= render 'form', room: @room %>

  <%= link_to 'Back', rooms_path %>

</div>

app/views/rooms/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @room.name %>
  </p>

  <%= link_to 'Edit', edit_room_path(@room) %> |
  <%= link_to 'Back', rooms_path %>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
  <div class="d-inline-flex">
    <h2 style="font-family: 'Reggae One', cursive; color: #D01117;">C</h2>
    <h2 style="font-family: 'Reggae One', cursive; color: #F3F0F9;">A</h2>
    <h2 style="font-family: 'Reggae One', cursive; color: #E3B505;">S</h2>
    <h2 style="font-family: 'Reggae One', cursive; color: #1EDD88;">A</h2>
  </div>
    <%#= image_tag "https://images.justlanded.com/directory_images/Vietnam/3/Cadasa-School-of-Language/photo/fb_image_scaled_65172_77587_logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboards_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Courses", courses_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Resources", dashboards_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Challenges", dashboards_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Messages", messages_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item active mr-3">
          <%= link_to "Chatrooms", rooms_path, class: "nav-link nav-items" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag(current_user.avatar_thumbnail, class: "avatar dropdown-toggle", alt: "avatar", id: "avatar navbarDropdown", data: { toggle: "dropdown"} ) %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", users_profile_path, class: "dropdown-item" %>
            <%= link_to "Bookings", courses_path, class: "dropdown-item" %>
            <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>